### PR TITLE
SDK-81: Refactor Workers resources to remove single-script code.

### LINKED ISSUE #387: worker_script doesnt work with multi-script for non enterprise accounts
Cloudflare launched multi script support for non enterprise accounts some week ago.
It's not possible to create a multiscript for non enterprise accounts using terraform plugin.

### Terraform Version
2:29 $ terraform -v
Terraform v0.12.2
+ provider.cloudflare (v1.16.0)

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_worker_script
- cloudflare_worker_route (?)

### Debug Output
```tf
module.maps.cloudflare_worker_script.script: Creating...

Error: error creating worker script: organization ID required for enterprise only request

  on terraform-modules/worker/script.tf line 6, in resource "cloudflare_worker_script" "script":
   6: resource "cloudflare_worker_script" "script" {
```

resource (module):
```tf
resource "cloudflare_worker_script" "script" {
  name    = "${var.name}"
  content = file("dist/${var.name}.js")
}
resource "cloudflare_worker_route" "script-route" {
  zone       = "${var.zone}"
  pattern    = "${var.pattern}"
  enabled    = var.enabled
  depends_on = [cloudflare_worker_script.script]
}
```

### Expected Behavior
scripts and routes should have been created

### Actual Behavior
nothing is created.

https://blog.cloudflare.com/just-write-code-improving-developer-experience-for-cloudflare-workers/#multiscript-for-all

### LINKED ISSUE #470: Refactor Workers resources to remove single-script code
Breaking change for v2.0

Multi-script support is open to everyone, let's remove single-script code paths.

### PR DESCRIPTION
**Pull request by patryk**
Closes #470
Closes #387

### CODE REVIEW

File: cloudflare/resource_cloudflare_worker_script.go [hunk 1]
```diff
@@ -53,26 +43,15 @@ type ScriptData struct {
...
-		id = "name:" + scriptName
-	} else {
-		params = cloudflare.WorkerRequestParams{
-			ZoneID: zoneID,
-		}
-		id = "zone:" + zoneID
+	params = cloudflare.WorkerRequestParams{
+		ScriptName: scriptName,
 	}
+	id = "name:" + scriptName
```
Comment (jRiest) [inline cloudflare/resource_cloudflare_worker_script.go]: We could just have the `scriptName` be the ID now that we don't need to differentiate between single-script and multi-script resources. However, I'm not sure what the backwards-compat concerns are around changing the ID format. It will work fine even if we leave the `name:` prefix.

File: cloudflare/resource_cloudflare_worker_script.go [hunk 2]
```diff
@@ -184,24 +163,8 @@ func resourceCloudflareWorkerScriptDelete(d *schema.ResourceData, meta interface
...
-	}
-
-	if scriptType == "name" {
-		d.Set("name", scriptId)
-	} else if scriptType == "zone" {
-		d.Set("zone_id", scriptId)
-	} else {
-		return nil, fmt.Errorf("invalid scriptType (\"%s\") specified, should be either \"name\" or \"zone\"", scriptType)
-	}
+	scriptID := d.Id()
```
Comment (jRiest) [inline cloudflare/resource_cloudflare_worker_script.go]: We may have a mismatch about ID format here. If the IDs follow the `name:{scriptName}` format, then would we still need people to specify `name:{scriptName}` when they import it?

File: cloudflare/resource_cloudflare_worker_script.go (hunk 1 above)
Comment (jacobbednarz) [reply cloudflare/resource_cloudflare_worker_script.go]: Seeing how this is going into 2.0, we can remove this and make a backwards incompatible change as long as we document the change and what people need to do to keep it working. Something we might want to consider though is a way for existing scripts to migrate to this though. In the past I've used [state migrations](https://www.terraform.io/docs/extend/resources/state-migration.html) however I'm not sure if they are different in 0.12.x now.

File: website/docs/r/worker_script.html.markdown [hunk 3]
```diff
@@ -38,30 +24,15 @@ resource "cloudflare_worker_script" "my_script" {
...
-* `ae36f999674d196762efcc5abb06b345` - the zone ID
-
-### multi-script
-
-To import a script from a multi-script account, use an id like `name:script_name`
+To import a script, use a script name, e.g. `script_name`
 
 ```
-$ terraform import cloudflare_worker_script.default name:script_name
+$ terraform import cloudflare_worker_script.default script_name
```
Comment (jacobbednarz) [inline website/docs/r/worker_script.html.markdown]: I usually shy away from using user provided names for things as they can change or be reused whereas the IDs that Cloudflare generate do not. Not a big deal but something worth raising I think to save us some hassle later.

Comment (patryk) [reply website/docs/r/worker_script.html.markdown]: Workers API has made a decision that script name is actually an ID too.
e.g.
```
    {
      "id": "example-script",
      "etag": "830924823da98de8429c9e9596ee79525aa2914fe32a19ca7e7aef77bfee2166",
      "modified_on": "2019-09-23T22:59:55.617676Z",
      "created_on": "2019-09-23T22:31:26.487806Z"
    },
```
becomes on API:
https://api.cloudflare.com/client/v4/accounts/cf0df04d99b840a890163aa457d8ee3d/workers/scripts/example-script

File: cloudflare/resource_cloudflare_worker_script.go (hunk 1 above)
Comment (patryk) [reply cloudflare/resource_cloudflare_worker_script.go]: Removed.

File: cloudflare/resource_cloudflare_worker_script.go (hunk 2 above)
Comment (patryk) [reply cloudflare/resource_cloudflare_worker_script.go]: Dropped prefix.

**Comment by patryk** [comment]
CI is all green. Please have a look at the changes.

File: website/docs/r/worker_script.html.markdown (hunk 3 above)
Comment (jacobbednarz) [reply website/docs/r/worker_script.html.markdown]: :cool: this is great to know!

**Comment by jacobbednarz** [comment]
This also closes #387
