### PR TITLE
Dns record fixes + expansion

### LINKED ISSUE #2: Cloudflare - SRV DNS records
_This issue was originally opened by @SystemZ as hashicorp/terraform#5732. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

I'm trying to add SRV record but there is an error with cloudflare API

```
Error applying plan:

1 error(s) occurred:

* cloudflare_record.ts3_official: Failed to create CloudFlare Record: API Error: Invalid service value.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Version

```
systemz@pc:~/Project/Infra/$ terraform -v
Terraform v0.6.13
```

Configuration for this SRV

```
resource "cloudflare_record" "ts3_official" {
    domain = "${var.cloudflare_domain}"
    name = "_ts3._udp.example.com."
    value = "0 0 9987 ts3.example.com."
    type = "SRV"
    ttl = 300
}
```

### LINKED ISSUE #7: Cloudflare record throwing Invalid dns record identifier
_This issue was originally opened by @jleclanche as hashicorp/terraform#13068. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Terraform 0.9.1, recently upgraded from 0.8 to the new backend system to the new backend system (I was using an s3 remote state before).

I have the following record:

```hcl
resource "cloudflare_record" "uploads-db" {
	domain = "example.com"
	name = "uploads-db"
	type = "CNAME"
	value = "${aws_db_instance.uploads-db.address}"
	proxied = false
}
```

I've had this record for a while, but now after the upgrade every time I do `terraform plan`, I get the following error:

```
Error refreshing state: 1 error(s) occurred:
2017/03/25 17:22:34 [DEBUG] plugin: terraform: local-exec-provisioner (internal) 2017/03/25 17:22:34 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/03/25 17:22:34 [DEBUG] plugin: terraform: aws-provider (internal) 2017/03/25 17:22:34 [DEBUG] plugin: waiting for all plugin processes to complete...

* cloudflare_record.uploads-db: cloudflare_record.uploads-db: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1002,\"message\":\"Invalid dns record identifier\"}],\"messages\":[],\"result\":null}"
```

I tried deleting and even tainting the record, but it *always* gives me that error, rendering terraform completely unusable :(

### LINKED ISSUE #21: 'terraform plan' crashes due to the rate limit in the CloudFlare API (1200 requests per 300 seconds)
Hello,
I am having an issue with this terraform provider, due to the rate limit in the CloudFlare API.

CloudFlare limits API requests to 1200 requests in 300 seconds.
https://support.cloudflare.com/hc/en-us/articles/200171456-How-many-API-calls-can-I-make-

```
grep resource foo.bar.tf | wc -l
615
```

### Terraform Version
```
$ terraform -v
Terraform v0.10.7
```
### Panic Output
```
* cloudflare_record.foo: cloudflare_record.foo: Error finding zone "foo.bar": ListZones command 
failed: error from makeRequest: HTTP status 429: content "{\"success\":false,\"errors\":[{\"code\":10100,\"message\":\"More than 1200 requests per 300 seconds
 reached. Please wait and consider throttling your request speed\"}],\"messages\":[],\"result\":null}"
```

### Expected Behavior
`terraform plan` should not crash

### Actual Behavior
`terraform plan` crashes due to the rate limit in the CloudFlare API

### Steps to Reproduce
`terraform plan` 

### References
https://support.cloudflare.com/hc/en-us/articles/200171456-How-many-API-calls-can-I-make-

### LINKED ISSUE #26: Add CAA to the valid DNS record types
Currently, valid types are "A", "AAAA", "CNAME", "TXT", "SRV", "LOC", "MX", "NS" or "SPF".
CAA is missing.

### PR DESCRIPTION
**Pull request by benjvi**
- Adds "data" input so that users can specify SRV, LOC records (fixes #2 )
- Adds some computed api fields to give users more context ('created_on', 'modified_on','proxiable','metadata')
- Force recreation on domain changes + removes redundant zone_id lookups (this will help with, but not resolve #21 )
- Set id blank when record is not found ( fixes #7 )
- Allow CAA records through validation ( fixes #26 )
- Now runs tests in parallel

### CODE REVIEW

File: cloudflare/resource_cloudflare_record.go [hunk 1]
```diff
@@ -128,16 +177,18 @@ func resourceCloudFlareRecordCreate(d *schema.ResourceData, meta interface{}) er
...
-
-	record, err := client.DNSRecord(zoneId, d.Id())
-	if err != nil {
-		return err
+		if strings.Contains(err.Error(), "Invalid dns record identifier") ||
+			strings.Contains(err.Error(), "HTTP status 404") {
+			log.Printf("[WARN] Removing record from state because it's not found in API")
+			d.SetId("")
+			return nil
+		} else {
```
Comment (catsby) [inline cloudflare/resource_cloudflare_record.go]: nit: no need for else here because of the return.

```go
if err!= nil {
  if stringsContains .... {
    /// 
    d.SetId("")
    return nil
  }
  
  return err
}
```

File: cloudflare/resource_cloudflare_record.go [hunk 2]
```diff
@@ -147,20 +198,26 @@ func resourceCloudFlareRecordRead(d *schema.ResourceData, meta interface{}) erro
 	d.Set("ttl", record.TTL)
 	d.Set("priority", record.Priority)
 	d.Set("proxied", record.Proxied)
-	d.Set("zone_id", zoneId)
+	d.Set("created_on", record.CreatedOn.Format(time.RFC3339Nano))
+	d.Set("data", expandStringMap(record.Data))
+	d.Set("modified_on", record.ModifiedOn.Format(time.RFC3339Nano))
+	d.Set("metadata", expandStringMap(record.Meta))
```
Comment (catsby) [inline cloudflare/resource_cloudflare_record.go]: For non-scalar values (Maps, Lists, Sets), please check the error:

```go
if err := d.Set("metadata", expandStringMap(record.Meta)); err != nil {
  log.Printf("[WARN] Error setting metadata: %s", err)  
}
```

File: cloudflare/resource_cloudflare_record.go (hunk 1 above)
Comment (catsby) [reply cloudflare/resource_cloudflare_record.go]: Applied in https://github.com/terraform-providers/terraform-provider-cloudflare/commit/f01532c4a37f894b2926b54bed9e5d21d19255cd

File: cloudflare/resource_cloudflare_record.go (hunk 2 above)
Comment (catsby) [reply cloudflare/resource_cloudflare_record.go]: Applied in https://github.com/terraform-providers/terraform-provider-cloudflare/commit/f01532c4a37f894b2926b54bed9e5d21d19255cd

**Comment by EpiqSty** [comment]
@catsby it's nice to hear, that #2 is fixed, but i am still getting errors while creating SRV records:

```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "cloudflare" (0.1.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.cloudflare: version = "~> 0.1"

Terraform has been successfully initialized!

[.....]

cloudflare_record._sipfederationtls__tcp_example_com_SRV: Creating...
  domain:   "" => "example.com"
  hostname: "" => "<computed>"
  name:     "" => "_sipfederationtls._tcp"
  proxied:  "" => "false"
  ttl:      "" => "3600"
  type:     "" => "SRV"
  value:    "" => "0 0 5061 sip.example.com"
  zone_id:  "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* cloudflare_record._sipfederationtls__tcp_example_com_SRV: 1 error(s) occurred:

* cloudflare_record._sipfederationtls__tcp_example_com_SRV: Failed to create record: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1004,\"message\":\"DNS Validation Error\",\"error_chain\":[{\"code\":9036,\"message\":\"Invalid or missing data for %s record\"}]}],\"messages\":[],\"result\":null}"

```

Should I await until next provider release or I could get last revision and build provider on my own and use it as a custom provider?

Thanks in advance!

**Comment by catsby** [comment]
Hey @EpiqSty – while the fix has been merged, there has been no new release since then. Here's a list of things coming in the next release:

- https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/CHANGELOG.md#011-unreleased

You are welcome to pull down the master branch of this repository and build the provider yourself! This requires Go 1.9 setup on your system, but after cloning the repository simply run `go install` on the machine to install it. You'll then need to be in the directory of your configuration and run `terraform init -upgrade` to grab the compiled version.

**Comment by EpiqSty** [comment]
@catsby , thanks for the quick reply!

Do you know anything about release plans? 

I mean for manual usage upgrading from sources is kind of OK, but as we are using terraform in CI/CD environment that will requires adjustment of Jenkins jobs in order to get custom provider on the Jenkins slaves and so on.

So, this is a question about the release date, basically ;)

If it in the near future (several weeks) we could create such records locally ( using custom provider builded from sources)  and push tfstates to our terraform repo.

But if we should wait for the next release several months, probably we should choose the option of using custom providers directly on the jenkins slaves.

**Comment by catsby** [comment]
I do not know the release date, other than "as soon as possible". There are some other PRs and features that I believe are requested in the next release. 

The release date is optimistically 0-7 days, pessimistically 2-3 weeks. I cannot promise either of those, though 😄

**Comment by EpiqSty** [comment]
well, it's good enough  - thanks ;)

**Comment by EpiqSty** [comment]
@catsby I have tested creation of SRV records with latest version, build from sources, but get the same error.
Maybe for SRV records we should specify structured data?
I saw something related in your commit:
allow users to specify structured data for records 41ef9b8
But I can't find any examples, how should we define such data. 
Should it be something like this ?

```
 resource "cloudflare_record" "_sipfederationtls__tcp_example_com_SRV" {
   domain  = "example.com"
   name    = "_sipfederationtls._tcp"
   type    = "SRV"
   value   = "0 0 5061 sip.example.com"
   ttl     = 1
   data { 
     priority = 1
     weight   = 1
     port     = 5061
     target   = "sip.example.com" 
     service  = "_sipfederationtls"
     proto    = "_tcp"
     name     = "example.com" }
 }

```
Unfortunately , Cloudflare API itself has no proper documentation about fields required for creating SRV records.
I have created support ticket about it, but at the moment they provided me just this advice:

> In the meantime, what I would suggest is you can create a SRV record via our UI and then you can use the API to do a GET request on the DNS records, that should show you all the fields that are required.

**Comment by EpiqSty** [comment]
Looks like I found the way how to define it:
```
resource "cloudflare_record" "_sipfederationtls__tcp_example_com_SRV" {
  domain  = "example.com"
  name    = "_sipfederationtls._tcp"
  type    = "SRV"
#  value   = "0 0 5061 sip.example.com"
  ttl     = 3600
  data {
    priority = 0
    weight   = 0
    port     = 5061
    target   = "sip.example.com"
    service  = "_sipfederationtls"
    proto    = "_tcp"
    name     = "example.com" }
}

[...]

cloudflare_record._sipfederationtls__tcp_example_com_SRV: Creating...
  created_on:    "" => "<computed>"
  data.%:        "" => "7"
  data.name:     "" => "example.com"
  data.port:     "" => "5061"
  data.priority: "" => "0"
  data.proto:    "" => "_tcp"
  data.service:  "" => "_sipfederationtls"
  data.target:   "" => "sip.example.com"
  data.weight:   "" => "0"
  domain:        "" => "example.com"
  hostname:      "" => "<computed>"
  metadata.%:    "" => "<computed>"
  modified_on:   "" => "<computed>"
  name:          "" => "_sipfederationtls._tcp"
  proxiable:     "" => "<computed>"
  proxied:       "" => "false"
  ttl:           "" => "3600"
  type:          "" => "SRV"
  value:         "" => "<computed>"
  zone_id:       "" => "<computed>"
cloudflare_record._sipfederationtls__tcp_example_com_SRV: Creation complete after 0s (ID: <removed>)
```
I left value commented just in order to mention, that SRV definition with "value" only ends up with error "Invalid or missing data for %s record", but the same record, defined as data structure works well.
